import Head from "next/head";
export default function Navbar() {
    return (
        <>
            <Head>
                <title>Pcology</title>
                <meta name="description" content="Generated by create next app" />

                <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" />
                <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
            </Head>
            <header>

                <div id="top-header">
                    <div class="container">
                        <ul class="header-links pull-left">
                            <li><a href="#"><i class="fa fa-phone"></i> 99999999999</a></li>
                            <li><a href="#"><i class="fa fa-envelope-o"></i> ssgkp.singh.com</a></li>
                            <li><a href="#"><i class="fa fa-map-marker"></i>273010 gkp Road</a></li>
                        </ul>
                        <ul class="header-links pull-right">
                            <li><a href="#"><i class="fa fa-dollar"></i> USD</a></li>
                            <li><a href="#"><i class="fa fa-user-o"></i> My Account</a></li>
                        </ul>
                    </div>
                </div>



                <div id="header">

                    <div class="container">

                        <div class="row">

                            <div class="col-md-3">
                                <div class="header-logo">
                                    <a href="/" class="logo">
                                        <img src="./img/pcology1.png" alt="" />
                                    </a>
                                </div>
                            </div>





                        </div>

                    </div>

                </div>

            </header>






        </>
    )
}